#+TITLE: Internship Report
#+AUTHOR: Ezequiel Torti Lopez
#+OPTIONS: num:nil ^:nil f:nil
#+LATEX_HEADER: \documentclass{article}
#+LATEX_HEADER: \usepackage{amscd}
#+LATEX_HEADER: \usepackage{wrapfig}
#+STARTUP: hideblocks
#+PROPERTY: session *R* 
#+PROPERTY: results output

#+begin_LaTeX
  \hypersetup{
    linkcolor=blue,
    pdfborder={0 0 0 0}
  }
  \lstset{basicstyle=\ttfamily\bfseries\small}
#+end_LaTeX

#+LaTeX: \begin{document}


#+LaTeX: \section{Motivation and Problem Statement}

Simulation is the third pillar of science, allowing to study complicated
phenomenons through complex models. When the size or complexity of the studied
models becomes too large, it is classical to leverage more resources through
Parallel Discrete-Event Simulation (PDES).  

Still, the parallel simulation of very fine grained applications deployed on
large-scale distributed systems (LSDS) remains challenging. As a matter of fact,
most simulators of Peer-to-Peer systems are sequential, despite the vast
literature on PDES over the last three decades.

dPeerSim is one of the very few existing PDES for P2P systems, but it presents
deceiving performance: it can achieve a decent speedup when increasing the
amount of logical processes (LP): from 4h with 2 LPs down to 1h with 16 LPs.
But it remains vastly inefficient when compared to sequential version of
PeerSim, that performs the same experiment in 50 seconds only. This calls for a
new parallel schema specifically tailored to this category of Discrete Event
Simulators.

Discrete Event Simulation of Distributed Applications classically alternates
between simulation phases where the models compute the next event date, and
phases where the application workload is executed.  We proposed
in~\cite{previous} to not split the simulation model across several computing
nodes, but instead to keep the model sequential and execute the application
workload in parallel when possible. We hypothesized that this would help
reducing the synchronization costs. We evaluate our contribution with very fine
grained workloads such as P2P protocols. These workloads are the most difficult
to execute efficiently in parallel because execution times are very short,
making it very difficult to amortize the synchronization times.

We implemented this parallel schema within the SimGrid framework, and showed
that the extra complexity does not endangers the performance since the
sequential version of SimGrid still outperforms several competing solutions when
our addition are present but disabled at run time.

To the best of our knowledge, it is the first time that a parallel simulation of
P2P system proves to be faster that the best known sequential execution. Yet,
the parallel simulation only outperforms sequential one when the amount of
processes becomes large enough. This is because of the pigonhole principle: when
the amount of processes increases, the average amount of processes that are
ready to run at each simulated timestamp (and can thus run in parallel)
increases. When simulating the Chord protocol, it takes 500,000 processes or
more to amortizing the synchronization costs, while the classical studies of the
literature usually involve less processes.

The current work aims at further improving the performance of our PDES, using
several P2P protocols as a workload. We investigate the possible inefficiency
and propose generic solutions that could be included in other similar simulators
of large-scale distributed systems, be them P2P simulators of cloud, HPC or
sensornets ones.

This paper is organized as follows: Section~\ref{sec:context} recaps the SimGrid
architecture and quickly presents the parallel execution schema detailed
in~\cite{previous}. Section~\ref{sec:parallel} explores several trade-offs for
the efficiency of the parallel sections. Section~\ref{sec:problem} analysis the
theoretical performance bound, and discusses the previous work at the light of
the Amhdal law.  Section~\ref{sec:adaptative} proposes an algorithm to
automatically tune the level of parallelism that is adapted to the simulated
application. Section~\ref{sec:cc} concludes this paper and discusses some future
work.


#+LaTeX: \section{Context}\label{sec:context}

In the previous work ~\cite{previous} we proposed to parallelize the execution
of the user code while keeping the simulation engine sequential.
This is enabled by applying classical concepts of OS design to this new context:
every interaction between the user processes and the simulated environment is
mediated by a specific layer that acts as the OS kernel.

Experimental results showed that the new design does not hinder the tool
scalability. In fact, the sequential version of SimGrid remains orders of magnitude
more scalable than state of the art simulators.
The difficulty to get a parallel version of a P2P simulator faster than its
sequential counterpart was also revealed, being the first time that a parallel
simulation of Chord runs faster than the best known sequential implementation.

A relevant result showed in the previous work is that the speedups only increased
up to a certain point when increasing the amount of working threads.
We also have proved that for small instances, parallelism actually hinders the
performance, and that the relative gain of parallelism seems even strictly increasing
with the system size. In particular, the constant model was benefited from parallelism
only after about 30000 nodes while the precise model had to reach about 500000
nodes for that. This can be explained using the Amdahl's law and taking in count
the code portions that do not run in parallel: it is much higher with the precise
model since we compute the hardware models sequentially.

Now we are closer to the optimal Amdahl's law threshold, that means, that we have
reach a limit on the parallelizable portions of the code. The remaining optimizations
seek for an ultimate speedup, trying to get a better parallel threshold dynamically
depending on the simulation, and better performance of the threads taking in count
their distribution on the CPU cores.

#+LaTeX: \section{Optimizations}\ref{sec:parallel}
#+LaTeX: \subsection{Parmap between N cores}
 \#proc. (1-5 --> sequential; 6-20 --> 4busy waiters; 20-inf --> 16 busy waiter).
#+LaTeX: \subsection{Busy Waiters}
 \#proc. (1-5 --> sequential; 6-20 --> 4busy waiters; 20-inf --> 16 busy waiter).
#+LaTeX: \subsection{Performance Regression Testing}

#+LaTeX: \section{Problem Analysis}\label{sec:problem}
#+LaTeX: \subsection{Optimal Amdhal's law threshold} %Also, the benchmarking not intrusive is here.
We want to find the maximum speedup achieved with our current parallel
model. For that, a test a benchmark test is run to get the timings of a
typical sequential and parallel executions. After that, and using
the Amdahl's law, we can retrieve the real speedup achieved with
our system.

But first we want to prove that our benchmarks are not intrusive,
that is, our measures do not really affect the overall performance
of the system. For that, the experiments are run with and without
benchmarking, and then a comparation of both is made to find if
there is a significative breach in the timings of both experiments.

#+name: bench-not-intrusive
#+begin_src R :results graphics :file bench-not-intrusive.pdf 
library('ggplot2')
library('gridExtra')
library('reshape')

orig_data = read.table("./optimizations_experiments/timings/total_times_noamdahl.log")
opt_data = read.table("./optimizations_experiments/timings/total_sum_times_amdahl.log")
orig_data = as.data.frame.matrix(orig_data)
opt_data = as.data.frame.matrix(opt_data)
data <- data.frame(nodes =  orig_data[1:4,1], 
                   t2nobench = orig_data[1:4,9],
                   t8nobench = orig_data[1:4,11],
                   t2bench = opt_data[1:4,9],
                   t8bench = opt_data[1:4,11])
data[, "diff2"] <- abs(data$t2nobench - data$t2bench)
data[, "diff8"] <- abs(data$t8nobench - data$t8bench)
data[, "sum2"] <- data$t2nobench + data$t2bench
data[, "sum8"] <- data$t8nobench + data$t8bench
data[, "avg2"] <- data$sum2 / 2
data[, "avg8"] <- data$sum8 / 2
data[, "pdiff2"] <- data$diff2 / data$avg2
data[, "pdiff8"] <- data$diff8 / data$avg8
data[, "diff2"] <- NULL
data[, "diff8"] <- NULL
data[, "sum2"] <- NULL
data[, "sum8"] <- NULL
data[, "avg2"] <- NULL
data[, "avg8"] <- NULL
data[, "t2nobench"] <- NULL
data[, "t8nobench"] <- NULL
data[, "t2bench"] <- NULL
data[, "t8bench"] <- NULL
df <- melt(data ,  id = 'nodes', variable_name = 'difference')
ggplot(df, aes(x=nodes,y=value, group=difference, colour=difference)) + geom_line() + scale_fill_hue() + ylim(0,0.3)
#+end_src
#+caption: Percentage difference of time between benchmarked and original version.
#+results:
[[file:bench-not-intrusive.pdf]]


As it can be seen in the Figure 1, the maximum difference in the execution
time of both versions is 15\%, which is not big enough to say that the
benchmark is intrusive\\

TODO: This is just an asumption. I think I need a stronger statistical fact
here to prove what I want. Also, is the percentage diff equation the best option?

As a conclusion, the benchmarking is not really intrusive for the computation,
since it does not affect the parallel nor sequential executions of the simulation
in a significant way.

To calculate the speedup obtained with our parallel model, the experiment was
ran with 1000, 3000, 5000 and 10000 nodes. But as it can be seen in the Figure,
the real speedup is achieved with bigger sizes.\\
TODO: is practically impossible to run simulation with 100k nodes, thows
segfault. Without that, there's no way to show that there is speedup.

#+name: amdahl-speedup
#+begin_src R :results graphics  :file amdahl-speedup.pdf
library('ggplot2')
library('gridExtra')
library('reshape')
orig_data = read.table("./optimizations_experiments/timings/total_times_noamdahl.log")
opt_data = read.table("./optimizations_experiments/timings/total_sum_times_amdahl.log")
opt_data2 = read.table("./optimizations_experiments/timings/total_sum_times_amdahl2.log")
orig_data = as.data.frame.matrix(orig_data)
opt_data = as.data.frame.matrix(opt_data)
opt_data2 = as.data.frame.matrix(opt_data2)
data <- data.frame(nodes =  orig_data[1:4,1], seq = orig_data[1:4,8], sumamd = opt_data[1:4,11], sumamd2 = opt_data2[1:4,11])
# an extra seq column to average would be good too.
data[, "avgamdahl"] <- colMeans(rbind(data[, "sumamd"], data[, "sumamd2"]), na.rm=TRUE)
data[, "speedup"] <- data[, "seq"] / data[, "avgamdahl"]
df <- melt(data ,  id = 'nodes', variable_name = 'speedup')
ggplot(data, aes(x=nodes,y=speedup, colour=speedup)) + geom_line() + scale_colour_continuous(guide=FALSE)
#+end_src
#+caption: Real speedup achieved using parallell mode in Chord simulation.
#+results:
[[file:amdahl-speedup.pdf]]


\subsection{Parallelizable portions of the problem}
XXX: Probably a comment of scheduling rounds and parallel/sequential execution.

This experiment will be based on a typical Chord simulation, and the data wanted
are the following: ID of each Scheduling Round, time taken by each Scheduling Round
and number of process executed in each scheduling round.

What we want to prove is that the limit on the speed up reached is due to the fact
that we are very closer to the limit of parallelizable portions of the system. As
it can be seen on the first graph, the amount of processes computed by each scheduling
round is only one most of the times, so the parallel execution is not possible in that
instances. The remaining processes are executed in parallel due to the parallel
execution threshold already setted up in SimGrid (which can be modified).

: #+name: sr-distribution
: #+begin_src R :results output graphics  :file sr-distribution.pdf
: library('ggplot2')
: library('gridExtra')
: library('reshape')

: sr_data = read.table("./optimizations_experiments/sr_counts/sr_total_1000.log")
: sr_data = as.data.frame.matrix(sr_data)
: ggplot(data=sr_data, geom="histogram", aes(x=V3)) + xlim(0,13) + geom_histogram(aes(y=..count../sum(..count..))) + xlab("Amount of processes") + ylab("Percentage of Scheduling Rounds") + theme(panel.background = element_blank()) + #scale_x_discrete(breaks = seq(1, 10))
: #+end_src
: #+caption: Proportion of scheduling rounds computing processes.
: #+results:
: [[file:sr-distribution.pdf]]

#+name: sr-times
#+begin_src R :results graphics  :file sr-times.pdf
library('ggplot2')
library('gridExtra')
library('plyr')
library('data.table')

temp = list.files(path='./optimizations_experiments/sr_counts', pattern="*3000\\_threads*", full.names = TRUE)
flist <- lapply(temp, read.table)
sr_data <- rbindlist(flist)
sr_data[, "V1"] <- NULL
sr_data = as.data.frame.matrix(sr_data)
#for the mean
df <- ddply(sr_data, .(V3), summarize, mean_value = mean(V2))
ggplot(data=df, geom="histogram", aes(x=V3, y=mean_value)) + xlab("") + ylab("") + geom_point(size = 3)  #+geom_line()
#+end_src
#+caption: Mean of times depending on the amount of processes of each scheduling round.
#+results:
[[file:sr-times.pdf]]

#+LaTeX: \section{Optimal threshold for parallel execution}
#+LaTeX: \subsection{Getting a real threshold over simulations}
The threshold wanted is how many processes are the right amount to be executed
in parallel when it is necessary, and when is it better to execute them in a
sequential way.
Initially, what we want is to find an optimal threshold for the beginning of
any simulation.
For that, a series of experiments have to be run using <version> of SimGrid.
That is why we test the performance of the engine in an exhaustive way,
benchmarking the scheduling rounds timings in parallel and sequential
executions, and finding the best average option for a simulation.

#+name: sr-par-threshold
#+begin_src R :results graphics  :file sr-par-threshold.pdf
library('ggplot2')
library('gridExtra')
library('plyr')
library('data.table')

#SEQUENTIAL
temp = list.files(path='./optimizations_experiments/sr_counts', pattern="threads2", full.names = TRUE)
flist <- lapply(temp, read.table)
sr_data <- rbindlist(flist) #TODO: SE PUEDE SACAR, CREO
sr_data[, "V1"] <- NULL
sr_data = as.data.frame.matrix(sr_data)
df <- ddply(sr_data, .(V3), summarize, mean_value = mean(V2))

#PARALLEL:
temp2 = list.files(path='./optimizations_experiments/sr_counts', pattern="threads4", full.names = TRUE)
flist2 <- lapply(temp2, read.table)
sr_data2 <- rbindlist(flist2) #TODO: SE PUEDE SACAR, CREO
sr_data2[, "V1"] <- NULL
sr_data2 = as.data.frame.matrix(sr_data2)
df2 <- ddply(sr_data2, .(V3), summarize, mean_value = mean(V2))

#merge this two datasets
df3 = merge(df, df2, by.x = 'V3', by.y = 'V3', incomparables = NULL)
df3[, 'speedup'] <- df3[,'mean_value.x'] / df3[, 'mean_value.y']
#for the mean
ggplot(data=df3, geom="histogram", aes(x=V3, y=speedup)) + xlab("") + ylab("") +geom_line()
#+end_src
#+caption: Speedup obtained in relation with the amount of processes computed by scheduling round.
#+results:
[[file:sr-par-threshold.pdf]]



#+LaTeX: \subsection{Adaptive algorithm to calculate threshold}
But finding an optimal threshold is not always the best option: some simulations
can take more time in each process and other less time. If a simulation has
very efficient processes, or processes that don't work too much, then the
threshold could be inefficient,
That's why an algorithm for a dynamic threshold calculation is proposed.
TODO: explanation of the heuristic...bla bla is the amount of time taken by
each scheduling round, and calculate on the fly a dynamic threshold to fit
better the simulation. Pseudocode

#+LaTeX: \subsection{Models used in the chord simulation}
\begin{itemize}
\item Workstation model: Default vm workstation model (as it appears on ./chord --help)
\item Network Model: LV08 (or Constant)
\item Cpu Model: Cas01
\end{itemize}

#+name: adapt-algorithm
#+begin_src R :results graphics  :file adapt-algorithm.pdf
library('ggplot2')
library('gridExtra')
library('reshape')

orig_data = read.table("./optimizations_experiments/dynamic_threshold/optimization3.dat")
opt_data = read.table("./optimizations_experiments/dynamic_threshold/optimization3_part2.dat")
orig_data = as.data.frame.matrix(orig_data)
opt_data = as.data.frame.matrix(opt_data)
#data <- data.frame(nodes =  orig_data[1:4,1], thr4const=orig_data[1:4,2], thr8const=orig_data[1:4,3], thr16const=orig_data[1:4,4], thr4prec=orig_data[1:4,5],thr8prec=orig_data[1:4,6],thr16prec=orig_data[1:4,7],optthr4const=opt_data[1:4,2], optthr8const=opt_data[1:4,3], optthr16const=opt_data[1:4,4], optthr4prec=opt_data[1:4,5], optthr8prec=opt_data[1:4,6],optthr16prec=opt_data[1:4,7])
data <- data.frame(nodes =  orig_data[1:4,1], thr4prec=orig_data[1:4,5],thr8prec=orig_data[1:4,6],thr16prec=orig_data[1:4,7],optthr4prec=opt_data[1:4,5], optthr8prec=opt_data[1:4,6],optthr16prec=opt_data[1:4,7])
df <- melt(data ,  id = 'nodes', variable_name = 'versions')
ggplot(df, aes(x=nodes,y=value, group=versions, colour=versions)) + geom_line() + scale_fill_hue()
#+end_src
#+caption: Chord simulation, Precise Model. Original version vs. Adaptative algorithm.
#+results:
[[file:adapt-algorithm.pdf]]


#+LaTeX: \section{Conclusion}\label{sec:cc}

#+LaTeX: \end{document}
